#alias duf='du -sk * | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'
#alias duf='du -sk * | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'
#alias series="flexget --series"
#alias hh="flexget --history"
#alias marvin="ssh arthur@marvin_kvm"
#alias micro="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@micro"
#alias centos="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no solifugo@centos"
#alias duf='sudo du -sk * | sort -n | perl -ne '\''($s,$f)=split(m{\t});for (qw(K M G)) {if($s<1024) {printf("%.1f",$s);print "$_\t$f"; last};$s=$s/1024}'\'
#alias discover="sudo nmap -sP 192.168.0.0/24 |grep -v latency |grep -v Address"
#alias config="nano -c /home/solifugo/.flexget/config.yml"
#alias stop="sudo /etc/init.d/transmission-daemon stop; sudo /etc/init.d/transmission-daemon status"
#alias start="sudo /etc/init.d/transmission-daemon start; sudo /etc/init.d/transmission-daemon status"
#alias added="grep -i added /home/solifugo/.flexget/flexget.log"
#alias rejected="grep -i rejected /home/solifugo/.flexget/flexget.log"
#alias log="tail -100 /home/solifugo/.flexget/flexget.log"
#alias flex="nohup flexget execute -v &"
alias ll="ls -lrth"
alias discover="sudo fing -n 192.168.0.130/24 -r 1 -o table,text,console"
alias duf='sudo du -schx .[!.]* * 2>/dev/null |sort -h'
alias dua='ncdu --color dark -rr -x /'
alias temp="sudo /usr/bin/sensors | grep "^Core" | grep -e '+.*C' | cut -f 2 -d '+' | cut -f 1 -d ' ' | sed 's/°C//'"
alias temp2="tail -5000 /home/solifugo/SERVER_TEMP.log  |grep Temperature"
alias cat='highlight -O ansi --force'
alias cath='highlight -O ansi --force'
alias cats='highlight -O ansi --force'
alias push="/home/solifugo/pushbullet-cli-master/pushbullet.py"
alias rac1-node1="ssh oracle@rac1-node1"
alias rac2-node1="ssh oracle@rac2-node1"
alias rac5-node1="ssh oracle@rac5-node1"
alias rac4-node1="ssh oracle@rac4-node1"
alias marvin="ssh root@marvin-centos"
alias aeon="ssh solifugo@aeon"
alias gridcoin="ssh solifugo@gridcoin"
alias monero="ssh solifugo@monero"
alias ubuntu="ssh solifugo@ubuntu"
alias freenas="ssh root@freenas"
alias oem="ssh root@oem"
alias monitor="ssh root@monitor"
alias list="virsh list"
alias lista="virsh list --all"
alias imac="ssh solifugo@imac"
alias server="ssh root@server"
alias wserver="ssh root@192.168.0.160 'racadm serveraction powerup'"
alias wfreenas="wakeonlan 9c:b6:54:09:2c:fc"
alias raspi2="ssh solifugo@raspi-router"
alias kmaster="ssh root@kmaster"
alias shut="sudo shutdown -h now"
#alias glances="glances --theme-white -2"
alias glances="glances -2"
alias fan="/home/solifugo/bin/IPMI_FAN" 
alias pmon="ps -ef |grep pmon |grep -v grep"
