. /vagrant/config/setup.env
/u01/app/oracle/product/21.3.0.0/dbhome_1/bin/dbca -silent -createDatabase \
  -templateName General_Purpose.dbc \
  -initParams db_recovery_file_dest_size=2G \
  -responseFile NO_VALUE \
  -gdbname CDB21 \
  -characterSet AL32UTF8 \
  -sysPassword Welcome1 \
  -systemPassword Welcome1 \ 
  -createAsContainerDatabase true \
  -numberOfPDBs 1 \
  -pdbName PDB211 \
  -pdbAdminPassword Welcome1 \
  -databaseType MULTIPURPOSE \
  -automaticMemoryManagement false \
  -totalMemory 2048 \
  -redoLogFileSize 50 \
  -emConfiguration NONE \
  -ignorePreReqs \
  -databaseConfigType RAC \
  -nodelist rac1-node1,rac1-node2 \
  -storageType ASM \
  -diskGroupName +DATA \
  -recoveryGroupName +RECO \
  -asmsnmpPassword Welcome1
/u01/app/oracle/product/19.3.0.0/dbhome_1/bin/dbca -silent -createDatabase \
  -templateName General_Purpose.dbc \
  -initParams db_recovery_file_dest_size=2G \
  -responseFile NO_VALUE \
  -gdbname CDB19 \
  -characterSet AL32UTF8 \
  -sysPassword Welcome1 \
  -systemPassword Welcome1 \ 
  -createAsContainerDatabase true \
  -numberOfPDBs 1 \
  -pdbName PDB191 \
  -pdbAdminPassword Welcome1 \
  -databaseType MULTIPURPOSE \
  -automaticMemoryManagement false \
  -totalMemory 2048 \
  -redoLogFileSize 50 \
  -emConfiguration NONE \
  -ignorePreReqs \
  -databaseConfigType RAC \
  -nodelist rac1-node1,rac1-node2 \
  -storageType ASM \
  -diskGroupName +DATA \
  -recoveryGroupName +RECO \
  -asmsnmpPassword Welcome1
