## -----------------------------------------------
## vagrant.yml for libVirt
## -----------------------------------------------
node1:
  vm_name: rac2-node1
  mem_size: 16384
  cpus: 24
  public_ip:  192.168.125.121
  vip_ip:     192.168.125.141
  private_ip: 192.168.200.111
  storage_pool_name: Vagrant_RAC_Storage

node2:
  vm_name: rac2-node2
  mem_size: 16384
  cpus: 24
  public_ip:  192.168.125.122
  vip_ip:     192.168.125.142
  private_ip: 192.168.200.112
  storage_pool_name: Vagrant_RAC_Storage

shared:
  prefix_name:   rac2
  # ---------------------------------------------
  domain  : localdomain
  scan_ip1: 192.168.125.145
  scan_ip2: 192.168.125.146
  scan_ip3: 192.168.125.147
  # ---------------------------------------------
  asm_disk_num:   6
  asm_disk_size: 20
  p1_ratio:      80
  asm_lib_type: 'ASMLIB'
  storage_pool_name: Vagrant_RAC_Storage
  # ---------------------------------------------

env:
  provider: libvirt
  # ---------------------------------------------
  gi_software:     LINUX.X64_213000_grid_home.zip
  db_software:     LINUX.X64_213000_db_home.zip
  # ---------------------------------------------
  root_password:   Welcome1
  grid_password:   Welcome1
  oracle_password: Welcome1
  sys_password:    Welcome1
  pdb_password:    Welcome1
  # ---------------------------------------------
  ora_languages:   en,en_GB
  # ---------------------------------------------
  nomgmtdb:        true
  orestart:        false
  # ---------------------------------------------
  db_name:         CDB21
  pdb_name:        PDB211
  db_type:         RAC
  cdb:             true
  # ---------------------------------------------
